import enum


class UserRole(str, enum.Enum):
    ADMIN = "ADMIN"
    MANAGER = "MANAGER"
    SALES_AGENT = "SALES_AGENT"
    VIEWER = "VIEWER"


class CustomerType(str, enum.Enum):
    IMPORTER = "IMPORTER"
    DISTRIBUTOR = "DISTRIBUTOR"
    RETAILER = "RETAILER"
    OTHER = "OTHER"


class CustomerStatus(str, enum.Enum):
    NEW = "NEW"
    CONTACTED = "CONTACTED"
    INTERESTED = "INTERESTED"
    QUOTE_SENT = "QUOTE_SENT"
    NEGOTIATING = "NEGOTIATING"
    WON = "WON"
    LOST = "LOST"
    FOLLOW_UP = "FOLLOW_UP"


class SalesStage(str, enum.Enum):
    LEAD = "LEAD"
    QUALIFIED = "QUALIFIED"
    PRODUCT_INTEREST = "PRODUCT_INTEREST"
    QUOTE_REQUESTED = "QUOTE_REQUESTED"
    QUOTE_SENT = "QUOTE_SENT"
    NEGOTIATION = "NEGOTIATION"
    CLOSED_WON = "CLOSED_WON"
    CLOSED_LOST = "CLOSED_LOST"


class ConversationStatus(str, enum.Enum):
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    CLOSED = "CLOSED"
    HUMAN_HANDOFF = "HUMAN_HANDOFF"


class MessageSenderType(str, enum.Enum):
    CUSTOMER = "CUSTOMER"
    AI_AGENT = "AI_AGENT"
    HUMAN_AGENT = "HUMAN_AGENT"


class MessageType(str, enum.Enum):
    TEXT = "TEXT"
    IMAGE = "IMAGE"
    DOCUMENT = "DOCUMENT"
    VIDEO = "VIDEO"
    AUDIO = "AUDIO"


class AvailabilityStatus(str, enum.Enum):
    AVAILABLE = "AVAILABLE"
    LOW_STOCK = "LOW_STOCK"
    OUT_OF_STOCK = "OUT_OF_STOCK"
    DISCONTINUED = "DISCONTINUED"


class QuoteStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    SENT = "SENT"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class FollowUpStatus(str, enum.Enum):
    PENDING = "PENDING"
    SENT = "SENT"
    CANCELLED = "CANCELLED"


class DocumentType(str, enum.Enum):
    PDF = "PDF"
    DOCX = "DOCX"
    XLSX = "XLSX"
    TXT = "TXT"


class ContentType(str, enum.Enum):
    WHATSAPP_STATUS = "WHATSAPP_STATUS"
    WHATSAPP_MESSAGE = "WHATSAPP_MESSAGE"
    INSTAGRAM_CAPTION = "INSTAGRAM_CAPTION"
    FACEBOOK_POST = "FACEBOOK_POST"
    COMMERCIAL_EMAIL = "COMMERCIAL_EMAIL"
    PRODUCT_ADVERTISEMENT = "PRODUCT_ADVERTISEMENT"
    IMPORTATION_CAMPAIGN = "IMPORTATION_CAMPAIGN"


class CampaignObjective(str, enum.Enum):
    GENERATE_LEADS = "GENERATE_LEADS"
    PROMOTE_PRODUCT = "PROMOTE_PRODUCT"
    GENERATE_SALES = "GENERATE_SALES"
    PROMOTE_IMPORTATION = "PROMOTE_IMPORTATION"
    CREATE_URGENCY = "CREATE_URGENCY"
    REACTIVATE_CUSTOMERS = "REACTIVATE_CUSTOMERS"


class Channel(str, enum.Enum):
    WHATSAPP = "WHATSAPP"
    MANUAL = "MANUAL"
    WEB = "WEB"


class Intent(str, enum.Enum):
    GREETING = "GREETING"
    PRODUCT_INQUIRY = "PRODUCT_INQUIRY"
    PRICE_REQUEST = "PRICE_REQUEST"
    QUOTE_REQUEST = "QUOTE_REQUEST"
    AVAILABILITY_REQUEST = "AVAILABILITY_REQUEST"
    IMPORTATION_REQUEST = "IMPORTATION_REQUEST"
    LOGISTICS_QUESTION = "LOGISTICS_QUESTION"
    PAYMENT_QUESTION = "PAYMENT_QUESTION"
    QUALITY_QUESTION = "QUALITY_QUESTION"
    CERTIFICATE_QUESTION = "CERTIFICATE_QUESTION"
    NEGOTIATION = "NEGOTIATION"
    FOLLOW_UP = "FOLLOW_UP"
    COMPLAINT = "COMPLAINT"
    HUMAN_AGENT_REQUEST = "HUMAN_AGENT_REQUEST"
    OTHER = "OTHER"
